DROP TABLE VETERINARIOS IF EXISTS;
CREATE TABLE VETERINARIOS (
ID INT AUTO_INCREMENT PRIMARY KEY,
NUMEROLICENCIA INT NOT NULL,
NOMBRE VARCHAR(25) NOT NULL,
APELLIDO VARCHAR(25) NOT NULL,
ESPECIALIDAD VARCHAR(25) NOT NULL
);

INSERT INTO VETERINARIOS VALUES (DEFAULT, 123,'JUAN', 'PEREZ','PERROS'),
(DEFAULT, 425,'PEPITO', 'TORRES','GATOS');
